<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>TestPackageSmokeTest</AssemblyName>
    <RootNamespace>TestPackageSmokeTest</RootNamespace>
    <Version>2.5.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestPackage.Core\TestPackage.Core.csproj" />
  </ItemGroup>

</Project>
