using System.Linq;
using System.Text;

namespace TestPackage.Core
{
    public static class ConfigWriter
    {
        public static string Write(ConfigModel m)
        {
            var sb = new StringBuilder();
            sb.AppendLine("; =============================================================================");
            sb.AppendLine("; TestPackage Configuration");
            sb.AppendLine("; =============================================================================");
            sb.AppendLine("; Generated by TestPackage");
            sb.AppendLine("; =============================================================================");
            sb.AppendLine();

            sb.AppendLine("[General]");
            sb.AppendLine($"AppName={m.AppName}");
            sb.AppendLine($"AppVersion={m.AppVersion}");
            sb.AppendLine($"AppPublisher={m.AppPublisher}");
            sb.AppendLine($"AppURL={m.AppURL}");
            sb.AppendLine($"AppGUID={m.AppGUID}");
            sb.AppendLine($"RequireAdmin={B(m.RequireAdmin)}");
            sb.AppendLine($"AppExeName={m.AppExeName}");
            sb.AppendLine($"InstallerExeName={m.InstallerExeName}");
            sb.AppendLine();

            sb.AppendLine("[WizardPages]");
            sb.AppendLine($"ShowWelcome={B(m.ShowWelcome)}");
            sb.AppendLine($"ShowEULA={B(m.ShowEULA)}");
            sb.AppendLine($"ShowInstallContext={B(m.ShowInstallContext)}");
            sb.AppendLine($"ShowTargetDirectory={B(m.ShowTargetDirectory)}");
            sb.AppendLine($"ShowComponents={B(m.ShowComponents)}");
            sb.AppendLine($"ShowDesktopShortcut={B(m.ShowDesktopShortcut)}");
            sb.AppendLine($"ShowStartMenuPin={B(m.ShowStartMenuPin)}");
            sb.AppendLine($"ShowRebootOption={B(m.ShowRebootOption)}");
            sb.AppendLine($"ShowActiveSetup={B(m.ShowActiveSetup)}");
            sb.AppendLine();

            sb.AppendLine("[EULA]");
            sb.AppendLine($"EULAText={m.EULAText}");
            sb.AppendLine();

            sb.AppendLine("[InstallContext]");
            sb.AppendLine($"DefaultContext={m.DefaultContext}");
            sb.AppendLine();

            sb.AppendLine("[TargetDirectory]");
            sb.AppendLine($"DefaultPath={m.DefaultPath}");
            sb.AppendLine($"AllowCustomPath={B(m.AllowCustomPath)}");
            sb.AppendLine();

            sb.AppendLine("[Components]");
            foreach (var c in m.Components)
                sb.AppendLine($"{c.Name}={B(c.DefaultSelected)}");
            sb.AppendLine();

            sb.AppendLine("[TestFiles]");
            sb.AppendLine($"Enabled={B(m.TestFilesEnabled)}");
            sb.AppendLine($"Files={m.TestFiles}");
            sb.AppendLine();

            sb.AppendLine("[Registry]");
            sb.AppendLine($"Enabled={B(m.RegistryEnabled)}");
            sb.AppendLine($"Entries={m.RegistryEntries}");
            sb.AppendLine();

            sb.AppendLine("[Shortcuts]");
            sb.AppendLine($"CreateDesktopShortcut={B(m.CreateDesktopShortcut)}");
            sb.AppendLine($"DesktopShortcutName={m.DesktopShortcutName}");
            sb.AppendLine($"CreateStartMenuEntry={B(m.CreateStartMenuEntry)}");
            sb.AppendLine($"StartMenuFolder={m.StartMenuFolder}");
            sb.AppendLine($"PinToStartMenu={B(m.PinToStartMenu)}");
            sb.AppendLine();

            sb.AppendLine("[FileAssociations]");
            sb.AppendLine($"Enabled={B(m.FileAssociationsEnabled)}");
            sb.AppendLine($"Associations={m.FileAssociations}");
            sb.AppendLine();

            sb.AppendLine("[ContextMenu]");
            sb.AppendLine($"Enabled={B(m.ContextMenuEnabled)}");
            sb.AppendLine($"Entries={m.ContextMenuEntries}");
            sb.AppendLine();

            sb.AppendLine("[EnvironmentVariables]");
            sb.AppendLine($"Enabled={B(m.EnvironmentVariablesEnabled)}");
            sb.AppendLine($"Variables={m.EnvironmentVariables}");
            sb.AppendLine();

            sb.AppendLine("[Services]");
            sb.AppendLine($"Enabled={B(m.ServicesEnabled)}");
            sb.AppendLine($"ServiceName={m.ServiceName}");
            sb.AppendLine($"ServiceDisplayName={m.ServiceDisplayName}");
            sb.AppendLine($"ServiceDescription={m.ServiceDescription}");
            sb.AppendLine($"ServiceStartType={m.ServiceStartType}");
            sb.AppendLine();

            sb.AppendLine("[ScheduledTasks]");
            sb.AppendLine($"Enabled={B(m.ScheduledTasksEnabled)}");
            sb.AppendLine($"TaskName={m.TaskName}");
            sb.AppendLine($"TaskDescription={m.TaskDescription}");
            sb.AppendLine($"TaskSchedule={m.TaskSchedule}");
            sb.AppendLine($"TaskTime={m.TaskTime}");
            sb.AppendLine();

            sb.AppendLine("[FirewallRules]");
            sb.AppendLine($"Enabled={B(m.FirewallRulesEnabled)}");
            sb.AppendLine($"Rules={m.FirewallRules}");
            sb.AppendLine();

            sb.AppendLine("[ProtocolHandlers]");
            sb.AppendLine($"Enabled={B(m.ProtocolHandlersEnabled)}");
            sb.AppendLine($"Protocols={m.ProtocolHandlers}");
            sb.AppendLine();

            sb.AppendLine("[ActiveSetup]");
            sb.AppendLine($"Enabled={B(m.ActiveSetupEnabled)}");
            sb.AppendLine($"StubPath={m.ActiveSetupStubPath}");
            sb.AppendLine($"Version={m.ActiveSetupVersion}");
            sb.AppendLine();

            sb.AppendLine("[AppPaths]");
            sb.AppendLine($"Enabled={B(m.AppPathsEnabled)}");
            sb.AppendLine($"ExeName={m.AppPathsExeName}");
            sb.AppendLine();

            sb.AppendLine("[Startup]");
            sb.AppendLine($"Enabled={B(m.StartupEnabled)}");
            sb.AppendLine($"Method={m.StartupMethod}");
            sb.AppendLine($"Scope={m.StartupScope}");
            sb.AppendLine();

            sb.AppendLine("[Fonts]");
            sb.AppendLine($"Enabled={B(m.FontsEnabled)}");
            sb.AppendLine($"FontFile={m.FontFile}");
            sb.AppendLine($"FontName={m.FontName}");
            sb.AppendLine();

            sb.AppendLine("[COMRegistration]");
            sb.AppendLine($"Enabled={B(m.COMRegistrationEnabled)}");
            sb.AppendLine($"CLSID={m.COMCLSID}");
            sb.AppendLine($"ProgID={m.COMProgID}");
            sb.AppendLine($"Description={m.COMDescription}");
            sb.AppendLine();

            sb.AppendLine("[Uninstall]");
            sb.AppendLine($"RegisterUninstaller={B(m.RegisterUninstaller)}");
            sb.AppendLine($"CleanFiles={B(m.CleanFiles)}");
            sb.AppendLine($"CleanRegistry={B(m.CleanRegistry)}");
            sb.AppendLine($"CleanShortcuts={B(m.CleanShortcuts)}");
            sb.AppendLine($"IntentionallyLeaveFiles={B(m.IntentionallyLeaveFiles)}");
            sb.AppendLine($"LeftoverFiles={m.LeftoverFiles}");
            sb.AppendLine($"IntentionallyLeaveRegistry={B(m.IntentionallyLeaveRegistry)}");
            sb.AppendLine($"LeftoverRegistry={m.LeftoverRegistry}");
            sb.AppendLine();

            sb.AppendLine("[Reboot]");
            sb.AppendLine($"PromptForReboot={B(m.PromptForReboot)}");
            sb.AppendLine($"ForceReboot={B(m.ForceReboot)}");
            sb.AppendLine();

            sb.AppendLine("[InstallerSize]");
            sb.AppendLine($"Enabled={B(m.InstallerSizeEnabled)}");
            sb.AppendLine($"SizeMB={m.InstallerSizeMB}");
            sb.AppendLine();

            sb.AppendLine("[CodeSigning]");
            sb.AppendLine($"Mode={m.CodeSigningMode}");
            sb.AppendLine($"PfxPath={m.CodeSigningPfxPath}");
            sb.AppendLine($"PfxPassword={m.CodeSigningPfxPassword}");
            sb.AppendLine($"TimestampUrl={m.CodeSigningTimestampUrl}");
            sb.AppendLine();

            sb.AppendLine("[UI]");
            sb.AppendLine($"BannerColor={m.BannerColor}");
            sb.AppendLine($"AccentColor={m.AccentColor}");
            sb.AppendLine($"ShowProgressBar={B(m.ShowProgressBar)}");
            sb.AppendLine($"SimulateInstallDelay={B(m.SimulateInstallDelay)}");
            sb.AppendLine($"InstallDelayMs={m.InstallDelayMs}");

            return sb.ToString();
        }

        private static string B(bool value) => value ? "true" : "false";
    }
}
