<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <AssemblyName>TestPackageApp</AssemblyName>
    <RootNamespace>TestPackageApp</RootNamespace>
    <Version>2.5.0</Version>
    <Company>RWK Systems</Company>
    <Product>TestPackage</Product>
    <Description>TestPackage - Installation test application by RWK Systems</Description>
    <ApplicationIcon>..\..\assets\icon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestPackage.Core\TestPackage.Core.csproj" />
  </ItemGroup>

</Project>
